#!/bin/sh

if test $# -le 1; then
	echo "Usage: nums option filename"

elif test $# -eq 2; then
	
	decision=$1
	m=`cat $2 | grep -c .`
	m=`expr $m + 1`
	m=`expr $m / 2`


	if test $decision -eq 0; then
		echo `sort -n $2 | head -1`
	elif test $decision -eq 1; then
		echo `sort -n $2 | tail -1`
	elif test $decision -eq 2; then		
		echo `sort -n $2 | head -$m | tail -1`
	else
		echo "Invalid option. Choose option between 0 and 2"
	fi
else
	echo "Usage: nums option filename"
fi

